from __future__ import annotations # Allows consistent typing of GUI fixtures.

import json # Creates isolated metadata lists and inspects saved border recipes.
import os # Detects whether a display is available for real Tk integration tests.
import sys # Makes the standalone tool importable during test discovery.
import time # Bounds asynchronous preview and batch completion waits.
import tkinter as tk # Exercises real controls and the Tk event loop.
import unittest # Uses the same standard-library runner as the image tests.
from collections.abc import Callable # Types event-loop completion predicates.
from contextlib import ExitStack # Restores every isolated module patch after each test.
from pathlib import Path # Keeps all test artwork and definitions inside temporary directories.
from tempfile import TemporaryDirectory # Prevents UI tests from writing repository assets.
from unittest.mock import patch # Replaces native dialogs while exercising their call sites.

from PIL import Image, ImageDraw # Generates deterministic artwork for authoring workflows.

sys.path.insert(0, str(Path(__file__).resolve().parents[1])) # Matches the standalone launcher's module lookup.
import sticker_creator as creator # Patches the composed tool's imported paths for isolation.
import sticker_creator_app as base # Patches base authoring roots and metadata list locations.
from sticker_border import BorderSettings # Provides exact recipe values for UI round-trip checks.
from sticker_border_controls import BorderControls # Finds shared border editors inside batch dialogs.
from sticker_creator_entry import StickerCreatorEntryApp # Exercises the same application class started by both launchers.


@unittest.skipUnless(os.environ.get("DISPLAY") or sys.platform in ("win32", "darwin"), "requires a desktop display or xvfb-run") # Keeps image and storage tests usable on headless machines.
class StickerCreatorUITests(unittest.TestCase): # Covers composed import, edit, picker, preview, and batch behaviour.
    def setUp(self) -> None: # Creates a real Tk application backed entirely by temporary artwork.
        self.stack: ExitStack = ExitStack() # Owns temporary directories, mocks, and path patches.
        self.addCleanup(self.stack.close) # Restores environment patches even if widget construction fails.
        self.root_path: Path = Path(self.stack.enter_context(TemporaryDirectory())) # Isolates test source and generated content.
        self.art_root: Path = self.root_path / "art" # Holds runtime PNGs generated by the tested UI.
        self.definition_root: Path = self.root_path / "definitions" # Holds Godot resources generated by the tested UI.
        self.source_root: Path = self.root_path / "source_art" # Holds preserved original PNGs and recipes.
        lists: Path = self.root_path / "lists.json" # Supplies valid packs, artists, and rarity metadata.
        lists.write_text(json.dumps({"packs": ["test_pack"], "artists": ["test_artist"], "rarities": ["Common"]}), encoding="utf-8") # Makes the form usable without manipulating unrelated repository metadata.
        self.stack.enter_context(patch.multiple(base, ART_ROOT=self.art_root, DEFINITION_ROOT=self.definition_root, SOURCE_ROOT=self.source_root, LISTS_JSON_PATH=lists, LISTS_RESOURCE_PATH=self.root_path / "lists.tres")) # Redirects the base authoring app to temporary paths.
        self.stack.enter_context(patch.multiple(creator, ART_ROOT=self.art_root, DEFINITION_ROOT=self.definition_root)) # Redirects imported constants used by editing and batch operations.
        self.errors = self.stack.enter_context(patch("tkinter.messagebox.showerror")) # Captures error dialogs for explicit assertions.
        self.stack.enter_context(patch("tkinter.messagebox.showinfo")) # Prevents success dialogs from blocking unattended verification.
        self.stack.enter_context(patch("tkinter.messagebox.askyesno", return_value=True)) # Confirms only deletions requested by an individual test.
        self.root: tk.Tk = tk.Tk() # Creates real widgets so geometry and callback wiring are exercised.
        self.addCleanup(self.root.destroy) # Destroys widgets and preview workers before restoring module patches.
        self.callback_errors: list[str] = [] # Records asynchronous Tk callback failures.
        self.root.report_callback_exception = lambda _kind, error, _trace: self.callback_errors.append(str(error)) # Turns callback exceptions into test-visible failures.
        self.app: StickerCreatorEntryApp = StickerCreatorEntryApp(self.root) # Uses the exact class launched on Linux and Windows.
        self.source: Path = self.root_path / "input" / "sample.png" # Supplies an external source outside the tool's output folder.
        self.source.parent.mkdir() # Creates the batch-selectable input directory.
        image: Image.Image = Image.new("RGBA", (96, 80)) # Creates transparent artwork with a visible silhouette.
        ImageDraw.Draw(image).polygon(((5, 70), (48, 4), (90, 70)), fill="#df6e41") # Makes cut geometry easy to distinguish from the source artwork.
        image.save(self.source) # Writes the fixture used by individual and batch imports.
        self.root.update() # Completes native widget geometry before tests inspect controls.

    def _fill_form(self) -> None: # Provides a valid individual import without invoking native file selection.
        self.app.art_var.set(str(self.source)) # Selects the original fixture for preview and import.
        self.app.name_var.set("first sticker") # Supplies an editable display name.
        self.app.pack_var.set("test_pack") # Selects a valid authored pack.
        self.app.artist_var.set("test_artist") # Selects a valid authored artist.
        self.app.rarity_var.set("Common") # Uses a normal supported rarity.

    def _wait_for(self, predicate: Callable[[], bool], timeout: float = 10.0) -> None: # Pumps real Tk events until asynchronous work completes.
        deadline: float = time.monotonic() + timeout # Bounds worker failures so tests cannot hang indefinitely.
        while not predicate() and time.monotonic() < deadline: # Allows queued preview and batch results to reach the UI.
            self.root.update() # Handles timers and widget callbacks on their owning thread.
            time.sleep(0.01) # Yields CPU to the worker between event-loop updates.
        self.root.update() # Applies the final queued status or image update.
        self.assertTrue(predicate(), "asynchronous tool operation did not finish") # Makes missed worker results a clear test failure.
        self.assertEqual(self.callback_errors, []) # Rejects Tk callbacks that failed while the operation was in progress.

    def _select_first(self) -> None: # Selects an authored sticker through the actual existing-sticker tree.
        self.app.sticker_tree.selection_set(self.app.sticker_tree.get_children()[0]) # Matches the UI selection consumed by edit and delete actions.

    def test_single_import_edit_recolour_rename_and_delete(self) -> None: # Checks that the complete UI saves and restores reversible border settings.
        self._fill_form() # Prepares an individual import using the original fixture image.
        chosen: BorderSettings = BorderSettings(10, 7, "#48b2dc") # Selects a distinctive custom border recipe.
        self.app._border_controls.set_settings(chosen) # Applies the same values available through the visible controls.
        self.app.create_sticker() # Imports the sticker through the composed tool's real action.
        self.errors.assert_not_called() # Requires the individual import to complete without hidden form or image errors.
        self.assertEqual(len(list(self.definition_root.glob("*.tres"))), 1) # Confirms a runtime sticker definition was created.
        self._select_first() # Opens the newly imported sticker for editing.
        self.app.edit_selected_sticker() # Restores the saved original and border recipe into the form.
        self.assertEqual(Path(self.app.art_var.get()), self.source_root / "000001.png") # Requires editing to use the preserved original rather than the bordered PNG.
        self.assertEqual(self.app._border_controls.settings(), chosen) # Restores all border controls exactly.
        recoloured: BorderSettings = BorderSettings(16, 12, "#b491ee") # Changes geometry and colour in the edit form.
        self.app._border_controls.set_settings(recoloured) # Applies the requested new backing recipe.
        self.app.name_var.set("renamed sticker") # Exercises the existing rename flow with stable authoring identities.
        self.app.create_sticker() # Saves the edit through the normal create/save action.
        self.errors.assert_not_called() # Requires rename and border regeneration to succeed together.
        self.assertTrue((self.art_root / "000001_renamed_sticker.png").is_file()) # Confirms runtime artwork follows the renamed definition.
        self.assertFalse((self.art_root / "000001_first_sticker.png").exists()) # Prevents stale duplicate runtime artwork after a rename.
        record = json.loads((self.source_root / "000001.json").read_text()) # Reads the persisted edit recipe independently of the controls.
        self.assertEqual(record["border"]["colour"], recoloured.colour) # Confirms the chosen colour was saved rather than merely previewed.
        self.assertEqual((self.source_root / "000001.png").read_bytes(), self.source.read_bytes()) # Preserves the exact original after multiple border passes.
        self._select_first() # Selects the renamed sticker for the existing delete action.
        self.app.delete_selected_sticker() # Deletes runtime and authoring files together.
        self.assertFalse(list(self.art_root.glob("*.png"))) # Removes the runtime artwork from the collection.
        self.assertFalse(list(self.source_root.glob("*.png"))) # Removes the deleted sticker's original archive.
        self.assertFalse(list(self.source_root.glob("*.json"))) # Removes the deleted sticker's border recipe before ID reuse.

    def test_colour_picker_and_preview_use_current_settings(self) -> None: # Verifies colour selection and asynchronous preview wiring.
        self._fill_form() # Selects artwork for the live preview.
        with patch("sticker_border_controls.colorchooser.askcolor", return_value=((50, 100, 150), "#326496")) as picker: # Supplies a deterministic native picker result.
            self.app._border_controls._choose_colour() # Exercises the actual custom colour picker action.
        picker.assert_called_once() # Requires the custom picker to be reachable from the controls.
        self.assertEqual(self.app._border_controls.settings().colour, "#326496") # Applies the picked colour to the saved recipe values.
        self._wait_for(lambda: "export preview" in self.app._border_controls._preview._caption.cget("text")) # Waits for final exported pixels to reach the preview canvas.
        self.assertIsNotNone(self.app._border_controls._preview._photo) # Requires an actual Tk image rather than only a status update.
        self.app._border_controls._width_var.set("not a number") # Exercises invalid intermediate user input.
        self._wait_for(lambda: "whole numbers" in self.app._border_controls._preview._caption.cget("text")) # Shows useful validation feedback without a modal loop.
        self.app.create_sticker() # Attempts to save with invalid border input.
        self.errors.assert_called_once() # Requires normal form validation to block the invalid save.
        self.assertFalse(list(self.definition_root.glob("*.tres"))) # Prevents half-created stickers from invalid settings.

    def test_batch_uses_frozen_recipe_and_releases_ui(self) -> None: # Checks the actual batch dialog, worker, and progress queue together.
        second: Path = self.source.parent / "second.png" # Creates another source image for a multi-item batch.
        Image.new("RGB", (65, 91), "#58a56f").save(second) # Exercises opaque artwork alongside the transparent fixture.
        with patch("sticker_creator.filedialog.askdirectory", return_value=str(self.source.parent)): # Selects only the temporary batch folder.
            self.app.open_batch_import() # Constructs the real batch dialog and its shared border controls.
        dialog: tk.Toplevel = next(widget for widget in self.root.winfo_children() if isinstance(widget, tk.Toplevel)) # Finds the newly opened modal batch editor.
        frame = dialog.winfo_children()[0] # Locates the dialog's form composition.
        controls: BorderControls = next(widget for widget in frame.winfo_children() if isinstance(widget, BorderControls)) # Uses the same controls offered to the user.
        recipe: BorderSettings = BorderSettings(9, 6, "#edbb57") # Chooses the recipe that should apply to every batch image.
        controls.set_settings(recipe) # Updates the batch-specific colour, width, and smoothing values.
        self.app._start_batch_import(dialog, [self.source, second], "test_pack", "test_artist", controls) # Starts the real background batch with a frozen recipe snapshot.
        self.assertTrue(self.app._content_busy) # Protects ID allocation and authoring records while the batch is active.
        self._fill_form() # Prepares a competing individual import while the batch owns content mutation.
        self.app.create_sticker() # Verifies the competing action cannot create an additional sticker.
        self._wait_for(lambda: not self.app._batch_busy) # Waits for queued completion to restore the authoring controls.
        self.errors.assert_not_called() # Requires the batch to complete without hidden worker errors.
        self.assertEqual(len(list(self.definition_root.glob("*.tres"))), 2) # Allows exactly the requested batch items and no competing import.
        for path in self.source_root.glob("*.json"): # Inspects each saved recipe independently of UI state.
            saved = json.loads(path.read_text())["border"] # Reads the recipe written by the worker.
            self.assertEqual(saved, {"width": recipe.width, "smoothing": recipe.smoothing, "colour": recipe.colour}) # Requires one consistent frozen recipe across the complete batch.
        self.assertFalse(self.app._content_busy) # Restores editing after a successful batch.
        self.assertFalse(self.app.commit_button.instate(["disabled"])) # Restores the normal content publication action.

    def test_batch_failure_reports_error_and_keeps_completed_stickers(self) -> None: # Verifies failure delivery after some images have already imported successfully.
        broken: Path = self.source.parent / "broken.png" # Represents a PNG with a valid signature but unreadable image content.
        broken.write_bytes(base.PNG_SIGNATURE + b"invalid image data") # Exercises decoding failure beyond the file-picker signature check.
        dialog: tk.Toplevel = tk.Toplevel(self.root) # Supplies the same control lifetime as a batch dialog.
        selection: tk.StringVar = tk.StringVar(dialog, str(self.source)) # Starts the preview on valid artwork before the batch begins.
        controls: BorderControls = BorderControls(dialog, selection, self.app._art_store.resolve_source) # Provides a validated shared recipe to the actual batch action.
        self.app._start_batch_import(dialog, [self.source, broken], "test_pack", "test_artist", controls) # Processes one valid image before encountering unreadable artwork.
        self._wait_for(lambda: not self.app._batch_busy) # Waits for failure feedback to release the UI.
        self.errors.assert_called_once() # Requires the worker error to reach the main-thread error dialog.
        self.assertIn("after creating 1 stickers", self.errors.call_args.args[1]) # Reports the exact number of successful imports before the failure.
        self.assertEqual(len(list(self.definition_root.glob("*.tres"))), 1) # Keeps the valid completed sticker available.
        self.assertEqual(len(list(self.art_root.glob("*.png"))), 1) # Leaves no orphaned output for the broken image.
        self.assertEqual(len(list(self.source_root.glob("*.json"))), 1) # Leaves no incomplete border recipe for the failed import.
        self.assertFalse(self.app._content_busy) # Restores authoring even after partial batch failure.

    def test_minimum_window_keeps_authoring_actions_accessible(self) -> None: # Guards against the new preview pushing essential controls outside the window.
        self.root.geometry("1040x800") # Exercises the supported minimum authoring window.
        self.root.update() # Allows grid and pack allocation to finish before measuring control bounds.
        for widget in (self.app._border_controls, self.app.sticker_tree, self.app.commit_button): # Checks border controls, existing-sticker selection, and publication access.
            with self.subTest(widget=type(widget).__name__): # Identifies the control whose layout becomes inaccessible.
                self.assertTrue(widget.winfo_ismapped()) # Requires the control to remain visible in the composed interface.
                self.assertLessEqual(widget.winfo_rooty() + widget.winfo_height(), self.root.winfo_rooty() + self.root.winfo_height()) # Prevents controls from extending below the supported window.
        self.assertGreaterEqual(self.app.sticker_tree.winfo_height(), 48) # Retains at least a usable header and sticker row for editing existing content.


if __name__ == "__main__": # Supports direct GUI verification on a desktop or under Xvfb.
    unittest.main() # Runs the composed tool integration suite.
