class_name StickerMesh
extends MeshInstance3D

const GRID_COLUMNS: int = 30 # Controls horizontal tessellation used by the peel shader.
const GRID_ROWS: int = 30 # Controls vertical tessellation used by the peel shader.
const PEEL_CURL_WIDTH: float = 0.34 # Defines the material arc length used by the rounded peel transition.
const PEEL_CURL_GROWTH: float = 0.45 # Defines how quickly the curl reaches its full radius during the opening part of a peel.
const ALPHA_CUTOFF: float = 0.08 # Defines the artwork alpha threshold treated as physical sticker material.
const SILHOUETTE_SIMPLIFY_EPSILON: float = 1.0 # Keeps the cached alpha contour accurate while removing redundant pixel-scale points.
const STICKER_SHADER: Shader = preload("res://shaders/sticker_material.gdshader") # Reuses one compiled shader across all sticker instances.

static var _normalized_silhouette_cache: Dictionary = {} # Shares all alpha-derived contour points between duplicate sticker instances so texture readback happens once per design.
static var _normalized_outer_contour_cache: Dictionary = {} # Shares ordered non-nested alpha contours used only for nearest-edge peel targeting.

var _artwork_size: Vector2 = Vector2.ONE # Stores the requested physical dimensions of the artwork and therefore the complete sticker sheet.
var _normalized_silhouette_points: PackedVector2Array = PackedVector2Array() # Stores every visible artwork contour point in centered normalized coordinates for exact peel-detachment support tests.
var _normalized_outer_contours: Array[PackedVector2Array] = [] # Stores ordered exterior alpha contours so peel targeting can move continuously along real sticker edges while ignoring interior holes.
var _material: ShaderMaterial # Stores the per-sticker shader parameters without duplicating shader code.

func configure(sticker_size: Vector2, sticker_texture: Texture2D, special_edition: bool = false) -> void: # Builds the static grid and binds artwork plus this copy's normal-or-special material state.
	_artwork_size = Vector2(maxf(sticker_size.x, 0.001), maxf(sticker_size.y, 0.001)) # Protects procedural geometry from invalid zero-sized sticker dimensions.
	_normalized_silhouette_points = _get_normalized_silhouette_points(sticker_texture) # Retrieves the cached real alpha contour used to know the exact frame the last attached material leaves the page.
	_normalized_outer_contours = _get_normalized_outer_contours(sticker_texture) # Retrieves ordered exterior contours for smooth nearest-point peel targeting without another image readback.
	mesh = _build_grid_mesh() # Creates the permanent subdivided surface used by GPU deformation.
	_material = ShaderMaterial.new() # Creates a unique parameter set for this sticker instance.
	_material.shader = STICKER_SHADER # Binds the shared realistic peel shader to the instance material.
	_material.set_shader_parameter("sticker_texture", sticker_texture) # Supplies the printed artwork to the shader.
	_material.set_shader_parameter("special_edition", special_edition) # Switches only this physical copy into the shiny gold-metal front treatment when required.
	_material.set_shader_parameter("curl_width", PEEL_CURL_WIDTH) # Keeps the shader curl geometry synchronized with the interaction model.
	_material.set_shader_parameter("curl_growth", PEEL_CURL_GROWTH) # Keeps the shader curl-growth rule synchronized with the full-peel threshold.
	_material.set_shader_parameter("alpha_cutoff", ALPHA_CUTOFF) # Keeps CPU silhouette extraction synchronized with the fragment shader's visible-material threshold.
	var surface_detail_seed: float = _build_surface_detail_seed() # Resolves a persistent book-placement identity when available and otherwise preserves runtime per-copy variation.
	_material.set_shader_parameter("surface_detail_offset", _build_surface_detail_offset(surface_detail_seed)) # Offsets grease and smudges uniquely while keeping saved book stickers visually stable across reconstruction.
	_material.set_shader_parameter("surface_detail_rotation", _build_surface_detail_rotation(surface_detail_seed)) # Rotates handling residue from the same persistent seed so duplicate designs retain distinct physical surface identities.
	material_override = _material # Applies the material to the complete grid with one draw surface.
	cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_DOUBLE_SIDED # Allows the lifted sticker to cast a real moving shadow on the page.
	custom_aabb = AABB(Vector3(-_artwork_size.x, -0.5, -_artwork_size.y), Vector3(_artwork_size.x * 2.0, 3.0, _artwork_size.y * 2.0)) # Prevents frustum culling while peeled vertices or the carried sheet move outside the original flat bounds.

func get_physical_size() -> Vector2: # Exposes the complete sticker sheet dimensions without leaking internal geometry state.
	return _artwork_size # Returns the artwork dimensions because no procedural margin is generated by the game.

func get_closest_outer_edge_point(local_target: Vector2) -> Vector2: # Returns the exact nearest point on the sticker's cached exterior alpha boundary in physical local coordinates.
	if _normalized_outer_contours.is_empty(): # Falls back to the complete artwork rectangle when texture CPU data could not provide an exterior contour.
		return _closest_point_on_artwork_rect(local_target) # Keeps the peel handle constrained to a sensible physical edge even for unavailable alpha data.
	var best_point: Vector2 = Vector2.ZERO # Stores the nearest physical point found across every exterior contour segment.
	var best_distance_squared: float = INF # Starts above every practical local-space distance so the first segment can establish a candidate.
	for normalized_contour: PackedVector2Array in _normalized_outer_contours: # Visits each disconnected exterior material island while excluding nested transparent-hole boundaries.
		var point_count: int = normalized_contour.size() # Stores contour size once because every valid polygon closes from its final point back to its first.
		if point_count <= 0: # Rejects malformed empty contour entries defensively.
			continue # Leaves the current best candidate unchanged.
		if point_count == 1: # Handles a pathological one-point contour without trying to construct a zero-length closing segment.
			var only_point: Vector2 = Vector2(normalized_contour[0].x * _artwork_size.x, normalized_contour[0].y * _artwork_size.y) # Converts the lone normalized point into physical sticker coordinates.
			var only_distance_squared: float = local_target.distance_squared_to(only_point) # Measures its proximity to the requested pointer target.
			if only_distance_squared < best_distance_squared: # Retains the lone point when it improves the current candidate.
				best_distance_squared = only_distance_squared # Stores the improved squared distance without a square root.
				best_point = only_point # Stores the matching physical edge point.
			continue # Moves to the next contour after resolving the degenerate case.
		for point_index: int in range(point_count): # Walks every ordered contour segment including the closing final-to-first edge.
			var next_index: int = (point_index + 1) % point_count # Wraps the final contour vertex back to the first so the exterior boundary is continuous.
			var segment_start: Vector2 = Vector2(normalized_contour[point_index].x * _artwork_size.x, normalized_contour[point_index].y * _artwork_size.y) # Converts this segment start into physical sticker coordinates.
			var segment_end: Vector2 = Vector2(normalized_contour[next_index].x * _artwork_size.x, normalized_contour[next_index].y * _artwork_size.y) # Converts the matching segment end into physical sticker coordinates.
			var candidate: Vector2 = _closest_point_on_segment(local_target, segment_start, segment_end) # Projects the requested pointer target continuously onto the actual contour segment rather than snapping to polygon vertices.
			var distance_squared: float = local_target.distance_squared_to(candidate) # Measures candidate proximity without an unnecessary square root.
			if distance_squared < best_distance_squared: # Keeps only the nearest exterior point across all disconnected visible islands.
				best_distance_squared = distance_squared # Stores the new best squared distance for later segment comparisons.
				best_point = candidate # Stores the physical local point used by the glowing peel handle and eventual peel origin.
	if best_distance_squared == INF: # Handles the defensive case where every cached contour entry was malformed.
		return _closest_point_on_artwork_rect(local_target) # Preserves a usable edge-constrained interaction through the rectangular fallback.
	return best_point # Returns the smooth nearest position on the real exterior alpha border.

func get_maximum_material_projection(direction: Vector2) -> float: # Returns the foremost visible artwork point along one peel direction for exact contact-loss detection.
	var normalized_direction: Vector2 = direction.normalized() # Protects support calculations from callers supplying a non-unit drag vector.
	if normalized_direction.is_zero_approx(): # Rejects a meaningless support direction before any contour work.
		return 0.0 # Returns a neutral projection because no peel direction currently exists.
	if _normalized_silhouette_points.is_empty(): # Falls back defensively when texture CPU data could not produce an alpha contour.
		var half_size: Vector2 = _artwork_size * 0.5 # Converts the artwork rectangle into positive half extents.
		return absf(normalized_direction.x) * half_size.x + absf(normalized_direction.y) * half_size.y # Returns the rectangular support distance without allocating temporary corner arrays.
	var maximum_projection: float = -INF # Starts below every practical local material projection.
	for normalized_point: Vector2 in _normalized_silhouette_points: # Walks only simplified alpha-contour vertices rather than every source pixel.
		var physical_point: Vector2 = Vector2(normalized_point.x * _artwork_size.x, normalized_point.y * _artwork_size.y) # Converts the centered normalized contour point into the sticker's real physical artwork dimensions.
		maximum_projection = maxf(maximum_projection, physical_point.dot(normalized_direction)) # Retains the artwork point farthest toward the moving peel front.
	return maximum_projection # Returns the true source-alpha support point without any generated border allowance.

func _get_normalized_silhouette_points(sticker_texture: Texture2D) -> PackedVector2Array: # Builds or retrieves simplified alpha geometry and populates both support-point and exterior-contour caches together.
	var cache_key: String = _get_silhouette_cache_key(sticker_texture) # Resolves the stable texture-and-dimensions identity shared by both silhouette caches.
	if _normalized_silhouette_cache.has(cache_key): # Reuses contour extraction for duplicate copies of the same sticker design.
		var cached_points: PackedVector2Array = _normalized_silhouette_cache[cache_key] # Narrows the cached Variant to the packed contour type.
		return cached_points # Returns the shared immutable contour without another GPU-to-CPU image readback.
	var silhouette_points: PackedVector2Array = PackedVector2Array() # Stores all simplified polygon vertices covering visible source alpha.
	var outer_contours: Array[PackedVector2Array] = [] # Stores only non-nested ordered contours for nearest-edge peel targeting.
	var source_image: Image = sticker_texture.get_image() # Reads the imported artwork image once while constructing both reusable contour cache entries.
	if source_image == null or source_image.is_empty(): # Handles textures whose CPU image representation is unavailable.
		_normalized_silhouette_cache[cache_key] = silhouette_points # Caches the empty support result so repeated instances do not retry a failed image readback.
		_normalized_outer_contour_cache[cache_key] = outer_contours # Caches the matching empty exterior result for the same failed source image.
		return silhouette_points # Lets projection and edge-target code use their safe rectangular fallbacks.
	var image_size: Vector2i = source_image.get_size() # Stores source pixel dimensions for bitmap creation and normalized-coordinate conversion.
	if image_size.x <= 0 or image_size.y <= 0: # Rejects malformed image dimensions defensively.
		_normalized_silhouette_cache[cache_key] = silhouette_points # Caches the unusable support result for duplicate instances.
		_normalized_outer_contour_cache[cache_key] = outer_contours # Caches the unusable exterior result for duplicate instances.
		return silhouette_points # Falls back to the artwork rectangle without risking division by zero.
	var alpha_bitmap: BitMap = BitMap.new() # Creates a one-bit representation of source alpha for efficient contour extraction.
	alpha_bitmap.create_from_image_alpha(source_image, ALPHA_CUTOFF) # Marks exactly the source pixels that pass the same visibility threshold as the sticker shader.
	var bitmap_rect: Rect2i = Rect2i(Vector2i.ZERO, image_size) # Covers the complete imported artwork bitmap for polygon extraction.
	var alpha_polygons: Array[PackedVector2Array] = alpha_bitmap.opaque_to_polygons(bitmap_rect, SILHOUETTE_SIMPLIFY_EPSILON) # Traces visible alpha using marching squares and simplifies redundant pixel-scale vertices.
	var normalized_contours: Array[PackedVector2Array] = [] # Preserves each polygon's point ordering before any flattening so nearest-edge queries can search complete segments.
	var inverse_width: float = 1.0 / float(image_size.x) # Precomputes horizontal normalization to avoid repeated divisions across contour points.
	var inverse_height: float = 1.0 / float(image_size.y) # Precomputes vertical normalization to avoid repeated divisions across contour points.
	for alpha_polygon: PackedVector2Array in alpha_polygons: # Visits every disconnected visible island because each can define the peel's final support point.
		if alpha_polygon.is_empty(): # Rejects malformed empty polygon entries without polluting either contour cache.
			continue # Moves directly to the next traced alpha polygon.
		var normalized_contour: PackedVector2Array = PackedVector2Array() # Stores this polygon separately so its ordered segments remain available for the peel handle.
		for pixel_point: Vector2 in alpha_polygon: # Converts each simplified marching-squares vertex into centered artwork coordinates.
			var normalized_point: Vector2 = Vector2(pixel_point.x * inverse_width - 0.5, pixel_point.y * inverse_height - 0.5) # Maps source pixels into the same centered local convention as the sticker mesh.
			normalized_contour.append(normalized_point) # Preserves this polygon's ordered edge sequence for continuous nearest-segment queries.
			silhouette_points.append(normalized_point) # Also stores the compact flattened contour point for inexpensive directional support tests during dragging.
		normalized_contours.append(normalized_contour) # Retains the completed ordered polygon independently from all other alpha islands.
	outer_contours = _filter_outer_contours(normalized_contours) # Excludes nested contours such as transparent holes while preserving disconnected exterior material islands.
	_normalized_silhouette_cache[cache_key] = silhouette_points # Shares the completed all-material support contour with every duplicate sticker instance.
	_normalized_outer_contour_cache[cache_key] = outer_contours # Shares the completed ordered exterior contours with every duplicate sticker instance.
	return silhouette_points # Returns the immutable normalized alpha contour used by exact peel completion.

func _get_normalized_outer_contours(sticker_texture: Texture2D) -> Array[PackedVector2Array]: # Retrieves the ordered exterior alpha contours populated alongside the normal silhouette cache.
	var cache_key: String = _get_silhouette_cache_key(sticker_texture) # Resolves the same stable texture-and-dimensions identity used by support-point extraction.
	if not _normalized_outer_contour_cache.has(cache_key): # Ensures both caches are generated together when exterior data is requested first.
		_get_normalized_silhouette_points(sticker_texture) # Performs the single source-image readback and populates the exterior cache as a side effect.
	var result: Array[PackedVector2Array] = [] # Creates a strongly typed per-instance array without exposing the mutable cached Array container directly.
	var cached_value: Variant = _normalized_outer_contour_cache.get(cache_key, []) # Reads the cached Variant defensively because static Dictionaries are intentionally untyped.
	if cached_value is not Array: # Rejects malformed cache state without risking a typed-array assignment error.
		return result # Leaves edge targeting on the safe rectangular fallback.
	var cached_array: Array = cached_value as Array # Narrows the cached container once before copying its packed contour values.
	for contour_value: Variant in cached_array: # Visits each cached exterior contour exactly once during sticker configuration.
		if contour_value is PackedVector2Array: # Accepts only the packed ordered point type produced by silhouette extraction.
			result.append(contour_value as PackedVector2Array) # Shares the immutable packed points while keeping the outer Array itself instance-owned.
	return result # Returns ordered exterior contours ready for frame-cheap nearest-edge queries.

func _get_silhouette_cache_key(sticker_texture: Texture2D) -> String: # Builds the stable identity shared by all cached geometry derived from one imported texture.
	var texture_path: String = sticker_texture.resource_path # Reads the stable resource path used by imported catalogue artwork.
	var cache_identity: String = texture_path if not texture_path.is_empty() else str(sticker_texture.get_instance_id()) # Falls back to runtime identity for dynamically created textures without a resource path.
	return "%s|%d|%d" % [cache_identity, sticker_texture.get_width(), sticker_texture.get_height()] # Includes dimensions so reimported artwork cannot reuse stale contour coordinates accidentally.

func _filter_outer_contours(contours: Array[PackedVector2Array]) -> Array[PackedVector2Array]: # Removes contours geometrically nested inside larger contours so transparent holes never become peel handles.
	var outer_contours: Array[PackedVector2Array] = [] # Stores only exposed exterior contours while preserving their original marching-squares order.
	for contour_index: int in range(contours.size()): # Tests each traced polygon against every larger polygon once during cache construction.
		var contour: PackedVector2Array = contours[contour_index] # Reads the candidate ordered polygon.
		if contour.size() < 2: # Rejects unusable contours before containment tests.
			continue # Leaves malformed geometry out of the peel-target cache.
		var contour_area: float = absf(_polygon_signed_area(contour)) # Measures candidate size so only genuinely larger polygons can contain it.
		var probe_point: Vector2 = contour[0] # Uses one boundary vertex as a stable representative point for nesting tests against other non-touching traced polygons.
		var nested: bool = false # Tracks whether this contour is an interior boundary rather than an exposed exterior island.
		for other_index: int in range(contours.size()): # Compares the candidate with every other traced polygon from the same alpha bitmap.
			if other_index == contour_index: # Skips self-containment because every polygon trivially contains its own boundary.
				continue # Moves directly to the next possible containing contour.
			var other: PackedVector2Array = contours[other_index] # Reads the possible containing polygon.
			if other.size() < 3 or absf(_polygon_signed_area(other)) <= contour_area + 0.0000001: # Requires a meaningfully larger closed polygon before performing the point-in-polygon test.
				continue # Avoids misclassifying separate or equal-size exterior islands.
			if _point_in_polygon(probe_point, other): # Detects a hole or other nested contour enclosed by a larger alpha boundary.
				nested = true # Marks this contour as non-exterior for peel targeting.
				break # Stops after the first confirmed containing polygon.
		if not nested: # Keeps every contour whose boundary is exposed to the outside of the sticker alpha shape.
			outer_contours.append(contour) # Preserves its ordered segments for smooth nearest-point tracking.
	if outer_contours.is_empty() and not contours.is_empty(): # Defends against pathological polygon data where containment classification removed every contour.
		return contours.duplicate() # Falls back to all traced contours rather than losing edge targeting entirely.
	return outer_contours # Returns only exposed alpha boundaries used by the glowing peel handle.

func _polygon_signed_area(polygon: PackedVector2Array) -> float: # Computes a lightweight shoelace area used only for one-time contour containment classification.
	if polygon.size() < 3: # Rejects open or degenerate contours that cannot enclose an area.
		return 0.0 # Returns neutral area for malformed input.
	var twice_area: float = 0.0 # Accumulates the signed doubled area without per-edge allocations.
	for point_index: int in range(polygon.size()): # Walks every ordered polygon edge including the closing final-to-first segment.
		var next_index: int = (point_index + 1) % polygon.size() # Wraps the closing edge back to the first vertex.
		twice_area += polygon[point_index].x * polygon[next_index].y - polygon[next_index].x * polygon[point_index].y # Adds this edge's shoelace cross product.
	return twice_area * 0.5 # Converts doubled signed area into the conventional polygon area value.

func _point_in_polygon(point: Vector2, polygon: PackedVector2Array) -> bool: # Tests strict geometric nesting without depending on version-sensitive Geometry2D helper signatures.
	if polygon.size() < 3: # Rejects contours that cannot enclose any area.
		return false # Reports no containment for degenerate input.
	var inside: bool = false # Tracks parity of horizontal ray crossings from the requested point.
	var previous_index: int = polygon.size() - 1 # Starts each edge pair with the closing final-to-first segment.
	for current_index: int in range(polygon.size()): # Walks every polygon edge once using the standard even-odd test.
		var current: Vector2 = polygon[current_index] # Reads the current edge endpoint.
		var previous: Vector2 = polygon[previous_index] # Reads the preceding edge endpoint.
		var crosses_vertical_range: bool = (current.y > point.y) != (previous.y > point.y) # Rejects edges whose endpoints lie on the same side of the horizontal test ray.
		if crosses_vertical_range: # Computes horizontal intersection only for edges that cross the point's Y level.
			var denominator: float = previous.y - current.y # Stores the edge's vertical span for the line intersection calculation.
			if absf(denominator) > 0.0000001: # Protects the division even though the vertical-range test already excludes perfectly horizontal edges.
				var intersection_x: float = (previous.x - current.x) * (point.y - current.y) / denominator + current.x # Finds where this polygon edge crosses the point's horizontal ray.
				if point.x < intersection_x: # Counts only intersections extending to the right of the test point.
					inside = not inside # Flips parity for each valid boundary crossing.
		previous_index = current_index # Advances the edge pair for the next polygon vertex.
	return inside # Reports true only when the point crossed the polygon boundary an odd number of times.

func _closest_point_on_segment(point: Vector2, segment_start: Vector2, segment_end: Vector2) -> Vector2: # Projects one point onto a finite 2D segment without allocating temporary geometry objects.
	var segment: Vector2 = segment_end - segment_start # Builds the segment direction in physical sticker coordinates.
	var length_squared: float = segment.length_squared() # Measures squared segment length for projection and zero-length detection.
	if length_squared <= 0.0000001: # Handles duplicate neighboring contour vertices safely.
		return segment_start # Treats the degenerate segment as its single endpoint.
	var factor: float = clampf((point - segment_start).dot(segment) / length_squared, 0.0, 1.0) # Projects onto the infinite line then clamps to this finite contour edge.
	return segment_start + segment * factor # Returns the continuous nearest point anywhere along this boundary segment.

func _closest_point_on_artwork_rect(point: Vector2) -> Vector2: # Provides a smooth perimeter fallback when alpha contour extraction is unavailable.
	var half_size: Vector2 = _artwork_size * 0.5 # Converts complete artwork dimensions into centered rectangle extents.
	var clamped: Vector2 = Vector2(clampf(point.x, -half_size.x, half_size.x), clampf(point.y, -half_size.y, half_size.y)) # Projects arbitrary local targets into or onto the artwork rectangle first.
	var distance_left: float = absf(clamped.x + half_size.x) # Measures distance to the left rectangle edge.
	var distance_right: float = absf(half_size.x - clamped.x) # Measures distance to the right rectangle edge.
	var distance_top: float = absf(clamped.y + half_size.y) # Measures distance to the top rectangle edge.
	var distance_bottom: float = absf(half_size.y - clamped.y) # Measures distance to the bottom rectangle edge.
	var minimum_distance: float = minf(minf(distance_left, distance_right), minf(distance_top, distance_bottom)) # Finds the nearest perimeter side for targets inside the rectangle.
	if point.x < -half_size.x or point.x > half_size.x or point.y < -half_size.y or point.y > half_size.y: # Detects targets already outside the rectangle where clamping naturally lands on the correct perimeter.
		return clamped # Returns the continuous clamped perimeter point directly.
	if is_equal_approx(minimum_distance, distance_left): # Chooses the nearest left side for an interior target.
		clamped.x = -half_size.x # Moves only the horizontal coordinate onto that perimeter edge.
	elif is_equal_approx(minimum_distance, distance_right): # Chooses the nearest right side when it is closer.
		clamped.x = half_size.x # Moves only the horizontal coordinate onto that perimeter edge.
	elif is_equal_approx(minimum_distance, distance_top): # Chooses the nearest top side when vertical distance wins.
		clamped.y = -half_size.y # Moves only the vertical coordinate onto that perimeter edge.
	else: # Uses the bottom side for the remaining nearest-edge case.
		clamped.y = half_size.y # Moves only the vertical coordinate onto that perimeter edge.
	return clamped # Returns a continuous edge point rather than snapping to rectangle corners.

func set_peel(grab_local: Vector2, drag_local: Vector2) -> void: # Updates only the lightweight uniforms needed for the current peel pose.
	_material.set_shader_parameter("grab_local", grab_local) # Sends the original local grab point into the deformation shader.
	_material.set_shader_parameter("drag_local", drag_local) # Sends the current local displacement into the deformation shader.

func clear_peel() -> void: # Returns the shader to the undeformed flat-sticker state.
	_material.set_shader_parameter("drag_local", Vector2.ZERO) # Removes all peel displacement while preserving the last grab point harmlessly.

func set_turnover(grab_local: Vector2, fold_axis_local: Vector2, angle: float) -> void: # Rotates the detached flat sheet around the grabbed material point so its adhesive side turns back to the printed face.
	var axis_3d: Vector3 = Vector3(fold_axis_local.x, 0.0, fold_axis_local.y).normalized() # Converts the in-plane fold axis into the sticker mesh's local 3D coordinates.
	var pivot_3d: Vector3 = Vector3(grab_local.x, 0.0, grab_local.y) # Converts the exact grabbed material point into the mesh's local 3D coordinates.
	var rotation_basis: Basis = Basis(axis_3d, angle) # Creates the requested physical rotation around the fold axis.
	var pivot_offset: Vector3 = pivot_3d - rotation_basis * pivot_3d # Computes the translation required to keep the grabbed material point fixed during rotation.
	transform = Transform3D(rotation_basis, pivot_offset) # Applies the turnover without moving the material point held by the player.

func clear_turnover() -> void: # Returns the detached visual to its normal printed-face-up transform.
	transform = Transform3D.IDENTITY # Removes all temporary turnover rotation and pivot translation.

func _build_grid_mesh() -> ArrayMesh: # Creates a fixed tessellated plane covering exactly the artwork rectangle.
	var vertices: PackedVector3Array = PackedVector3Array() # Stores grid vertex positions across the complete artwork rectangle.
	var normals: PackedVector3Array = PackedVector3Array() # Stores initial upward normals before shader deformation.
	var uvs: PackedVector2Array = PackedVector2Array() # Stores normal zero-to-one artwork coordinates across the sticker surface.
	var indices: PackedInt32Array = PackedInt32Array() # Stores indexed triangles with Godot's clockwise front-face winding.
	var vertex_columns: int = GRID_COLUMNS + 1 # Calculates the number of vertices across the grid including both edges.
	for row: int in range(GRID_ROWS + 1): # Walks every horizontal row of the tessellated sticker.
		var artwork_v: float = float(row) / float(GRID_ROWS) # Converts the row directly into source artwork UV space.
		var local_z: float = (artwork_v - 0.5) * _artwork_size.y # Converts the normalized row into centered physical sticker space.
		for column: int in range(GRID_COLUMNS + 1): # Walks every vertex across the current grid row.
			var artwork_u: float = float(column) / float(GRID_COLUMNS) # Converts the column directly into source artwork UV space.
			var local_x: float = (artwork_u - 0.5) * _artwork_size.x # Converts the normalized column into centered physical sticker space.
			vertices.append(Vector3(local_x, 0.0, local_z)) # Adds one flat material point to the sticker mesh.
			normals.append(Vector3.UP) # Gives the undeformed printed face an upward physical normal.
			uvs.append(Vector2(artwork_u, artwork_v)) # Stores the exact source artwork UV coordinate with no overscan or generated margin.
	for row: int in range(GRID_ROWS): # Walks each grid cell vertically to create indexed triangles.
		for column: int in range(GRID_COLUMNS): # Walks each grid cell horizontally to create indexed triangles.
			var top_left: int = row * vertex_columns + column # Finds the upper-left vertex of the current cell.
			var top_right: int = top_left + 1 # Finds the upper-right vertex of the first triangle.
			var bottom_left: int = top_left + vertex_columns # Finds the lower-left vertex of the current cell.
			var bottom_right: int = bottom_left + 1 # Finds the lower-right vertex of the current cell.
			indices.append(top_left) # Begins the first clockwise triangle in the cell.
			indices.append(top_right) # Adds the second vertex of the first triangle.
			indices.append(bottom_right) # Completes the first triangle across the cell diagonal.
			indices.append(top_left) # Begins the second clockwise triangle in the cell.
			indices.append(bottom_right) # Adds the second vertex of the second triangle.
			indices.append(bottom_left) # Completes the second triangle across the remaining half of the cell.
	var arrays: Array = [] # Creates the fixed Godot mesh-array container.
	arrays.resize(Mesh.ARRAY_MAX) # Sizes the container to the complete Mesh.ArrayType layout expected by ArrayMesh.
	arrays[Mesh.ARRAY_VERTEX] = vertices # Supplies procedural positions to the mesh surface.
	arrays[Mesh.ARRAY_NORMAL] = normals # Supplies initial normals to the mesh surface.
	arrays[Mesh.ARRAY_TEX_UV] = uvs # Supplies exact artwork coordinates to the mesh surface.
	arrays[Mesh.ARRAY_INDEX] = indices # Supplies indexed topology to the mesh surface.
	var array_mesh: ArrayMesh = ArrayMesh.new() # Creates the GPU mesh resource that owns the sticker surface.
	array_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays) # Commits the complete tessellated sticker as one efficient triangle surface.
	return array_mesh # Returns the finished static grid ready for shader deformation.

func _build_surface_detail_seed() -> float: # Resolves the identity used to generate this copy's grease and smudge pattern.
	var parent_node: Node = get_parent() # Reads the owning Sticker node whose book reconstruction name contains its persistent placement identity.
	if parent_node != null: # Checks for a composed Sticker owner before attempting to inspect its identity.
		var persistent_identity: String = str(parent_node.name) # Reads the owner name without introducing another persisted field or save-version migration.
		if persistent_identity.begins_with("sticker_"): # Recognizes the stable placement identifiers already written into sticker-book saves.
			return float(_hash_surface_identity(persistent_identity)) # Converts the persistent identity into deterministic procedural entropy that survives node reconstruction.
	return float(get_instance_id()) # Keeps non-book previews, shop sheets, and other temporary sticker meshes independently varied at runtime.

func _hash_surface_identity(identity: String) -> int: # Produces a stable integer hash from a persistent placement identifier without depending on runtime object identity.
	var hash_value: int = 2166136261 # Seeds the lightweight FNV-style hash with a fixed non-zero basis.
	var identity_bytes: PackedByteArray = identity.to_utf8_buffer() # Converts the short placement identifier once so hashing remains independent of locale or platform text representation.
	for byte_value: int in identity_bytes: # Mixes every identifier byte exactly once during sticker configuration.
		hash_value = ((hash_value ^ byte_value) * 16777619) & 0x7fffffff # Keeps the deterministic result positive and safely representable when converted to a floating-point procedural seed.
	return hash_value # Returns the persistent per-placement seed shared by every reconstruction of this physical sticker.

func _build_surface_detail_offset(surface_seed: float) -> Vector2: # Builds a procedural handling offset from either persistent placement identity or temporary runtime identity.
	var offset_x: float = _hash_float(surface_seed * 0.173 + 11.0) # Produces one deterministic horizontal offset for the grease texture.
	var offset_y: float = _hash_float(surface_seed * 0.379 + 37.0) # Produces one deterministic vertical offset for the grease texture.
	return Vector2(offset_x, offset_y) * 8.0 - Vector2.ONE * 4.0 # Spreads handling patterns broadly so duplicate sticker designs do not share the same residue placement.

func _build_surface_detail_rotation(surface_seed: float) -> float: # Builds one procedural handling rotation from the same per-copy identity used by the offset.
	return _hash_float(surface_seed * 0.613 + 73.0) * TAU # Converts a deterministic pseudo-random value into a full-angle rotation in radians.

func _hash_float(seed: float) -> float: # Generates a cheap deterministic pseudo-random scalar in the zero-to-one range without allocating a RandomNumberGenerator.
	var hashed_value: float = sin(seed) * 43758.5453123 # Produces the signed pseudo-random source value used by the lightweight per-instance hash.
	return hashed_value - floorf(hashed_value) # Reproduces shader-style fractional behavior with the typed GDScript floor function.
