class_name StickerMesh
extends MeshInstance3D

const GRID_COLUMNS: int = 30 # Controls horizontal tessellation used by the peel shader.
const GRID_ROWS: int = 30 # Controls vertical tessellation used by the peel shader.
const PEEL_CURL_WIDTH: float = 0.34 # Defines the material arc length used by the rounded peel transition.
const PEEL_CURL_GROWTH: float = 0.45 # Defines how quickly the curl reaches its full radius during the opening part of a peel.
const ALPHA_CUTOFF: float = 0.08 # Defines the artwork alpha threshold treated as physical sticker material.
const SILHOUETTE_SIMPLIFY_EPSILON: float = 1.0 # Keeps the cached alpha contour accurate while removing redundant pixel-scale points.
const STICKER_SHADER: Shader = preload("res://shaders/sticker_material.gdshader") # Reuses one compiled shader across all sticker instances.

static var _normalized_silhouette_cache: Dictionary = {} # Shares alpha-derived contour points between duplicate sticker instances so texture readback happens once per design.

var _artwork_size: Vector2 = Vector2.ONE # Stores the requested physical dimensions of the artwork and therefore the complete sticker sheet.
var _normalized_silhouette_points: PackedVector2Array = PackedVector2Array() # Stores the visible artwork contour in centered normalized coordinates for exact peel-detachment support tests.
var _material: ShaderMaterial # Stores the per-sticker shader parameters without duplicating shader code.

func configure(sticker_size: Vector2, sticker_texture: Texture2D) -> void: # Builds the static grid and binds the artwork used by this sticker.
	_artwork_size = Vector2(maxf(sticker_size.x, 0.001), maxf(sticker_size.y, 0.001)) # Protects procedural geometry from invalid zero-sized sticker dimensions.
	_normalized_silhouette_points = _get_normalized_silhouette_points(sticker_texture) # Retrieves the cached real alpha contour used to know the exact frame the last attached material leaves the page.
	mesh = _build_grid_mesh() # Creates the permanent subdivided surface used by GPU deformation.
	_material = ShaderMaterial.new() # Creates a unique parameter set for this sticker instance.
	_material.shader = STICKER_SHADER # Binds the shared realistic peel shader to the instance material.
	_material.set_shader_parameter("sticker_texture", sticker_texture) # Supplies the printed artwork to the shader.
	_material.set_shader_parameter("curl_width", PEEL_CURL_WIDTH) # Keeps the shader curl geometry synchronized with the interaction model.
	_material.set_shader_parameter("curl_growth", PEEL_CURL_GROWTH) # Keeps the shader curl-growth rule synchronized with the full-peel threshold.
	_material.set_shader_parameter("alpha_cutoff", ALPHA_CUTOFF) # Keeps CPU silhouette extraction synchronized with the fragment shader's visible-material threshold.
	_material.set_shader_parameter("surface_detail_offset", _build_surface_detail_offset()) # Gives each sticker copy a slightly different smudge and scratch layout.
	_material.set_shader_parameter("surface_detail_rotation", _build_surface_detail_rotation()) # Rotates the procedural realism texture so duplicates do not look stamped from the same wear pattern.
	material_override = _material # Applies the material to the complete grid with one draw surface.
	cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_DOUBLE_SIDED # Allows the lifted sticker to cast a real moving shadow on the page.
	custom_aabb = AABB(Vector3(-_artwork_size.x, -0.5, -_artwork_size.y), Vector3(_artwork_size.x * 2.0, 3.0, _artwork_size.y * 2.0)) # Prevents frustum culling while peeled vertices or the carried sheet move outside the original flat bounds.

func get_physical_size() -> Vector2: # Exposes the complete sticker sheet dimensions without leaking internal geometry state.
	return _artwork_size # Returns the artwork dimensions because no procedural margin is generated by the game.

func get_maximum_material_projection(direction: Vector2) -> float: # Returns the foremost visible artwork point along one peel direction for exact contact-loss detection.
	var normalized_direction: Vector2 = direction.normalized() # Protects support calculations from callers supplying a non-unit drag vector.
	if normalized_direction.is_zero_approx(): # Rejects a meaningless support direction before any contour work.
		return 0.0 # Returns a neutral projection because no peel direction currently exists.
	if _normalized_silhouette_points.is_empty(): # Falls back defensively when texture CPU data could not produce an alpha contour.
		var half_size: Vector2 = _artwork_size * 0.5 # Converts the artwork rectangle into positive half extents.
		return absf(normalized_direction.x) * half_size.x + absf(normalized_direction.y) * half_size.y # Returns the rectangular support distance without allocating temporary corner arrays.
	var maximum_projection: float = -INF # Starts below every practical local material projection.
	for normalized_point: Vector2 in _normalized_silhouette_points: # Walks only simplified alpha-contour vertices rather than every source pixel.
		var physical_point: Vector2 = Vector2(normalized_point.x * _artwork_size.x, normalized_point.y * _artwork_size.y) # Converts the centered normalized contour point into the sticker's real physical artwork dimensions.
		maximum_projection = maxf(maximum_projection, physical_point.dot(normalized_direction)) # Retains the artwork point farthest toward the moving peel front.
	return maximum_projection # Returns the true source-alpha support point without any generated border allowance.

func _get_normalized_silhouette_points(sticker_texture: Texture2D) -> PackedVector2Array: # Builds or retrieves a simplified alpha contour in centered normalized artwork coordinates.
	var texture_path: String = sticker_texture.resource_path # Reads the stable resource path used by imported catalogue artwork.
	var cache_identity: String = texture_path if not texture_path.is_empty() else str(sticker_texture.get_instance_id()) # Falls back to the runtime object identity for dynamically created textures without a resource path.
	var cache_key: String = "%s|%d|%d" % [cache_identity, sticker_texture.get_width(), sticker_texture.get_height()] # Includes dimensions so reimported artwork cannot reuse stale contour coordinates accidentally.
	if _normalized_silhouette_cache.has(cache_key): # Reuses contour extraction for duplicate copies of the same sticker design.
		var cached_points: PackedVector2Array = _normalized_silhouette_cache[cache_key] # Narrows the cached Variant to the packed contour type.
		return cached_points # Returns the shared immutable contour without another GPU-to-CPU image readback.
	var silhouette_points: PackedVector2Array = PackedVector2Array() # Stores all simplified polygon vertices covering visible source alpha.
	var source_image: Image = sticker_texture.get_image() # Reads the imported artwork image once while constructing the reusable contour cache entry.
	if source_image == null or source_image.is_empty(): # Handles textures whose CPU image representation is unavailable.
		_normalized_silhouette_cache[cache_key] = silhouette_points # Caches the empty result so repeated instances do not retry a failed image readback.
		return silhouette_points # Lets projection code use its safe rectangular fallback.
	var image_size: Vector2i = source_image.get_size() # Stores source pixel dimensions for bitmap creation and normalized-coordinate conversion.
	if image_size.x <= 0 or image_size.y <= 0: # Rejects malformed image dimensions defensively.
		_normalized_silhouette_cache[cache_key] = silhouette_points # Caches the unusable result for duplicate instances.
		return silhouette_points # Falls back to the artwork rectangle without risking division by zero.
	var alpha_bitmap: BitMap = BitMap.new() # Creates a one-bit representation of source alpha for efficient contour extraction.
	alpha_bitmap.create_from_image_alpha(source_image, ALPHA_CUTOFF) # Marks exactly the source pixels that pass the same visibility threshold as the sticker shader.
	var bitmap_rect: Rect2i = Rect2i(Vector2i.ZERO, image_size) # Covers the complete imported artwork bitmap for polygon extraction.
	var alpha_polygons: Array[PackedVector2Array] = alpha_bitmap.opaque_to_polygons(bitmap_rect, SILHOUETTE_SIMPLIFY_EPSILON) # Traces visible alpha using marching squares and simplifies redundant pixel-scale vertices.
	var inverse_width: float = 1.0 / float(image_size.x) # Precomputes horizontal normalization to avoid repeated divisions across contour points.
	var inverse_height: float = 1.0 / float(image_size.y) # Precomputes vertical normalization to avoid repeated divisions across contour points.
	for alpha_polygon: PackedVector2Array in alpha_polygons: # Visits every disconnected visible island because each can define the peel's final support point.
		for pixel_point: Vector2 in alpha_polygon: # Converts each simplified marching-squares vertex into centered artwork coordinates.
			var normalized_point: Vector2 = Vector2(pixel_point.x * inverse_width - 0.5, pixel_point.y * inverse_height - 0.5) # Maps source pixels into the same centered local convention as the sticker mesh.
			silhouette_points.append(normalized_point) # Stores the compact contour point for inexpensive directional support tests during dragging.
	_normalized_silhouette_cache[cache_key] = silhouette_points # Shares the completed contour with every duplicate sticker instance.
	return silhouette_points # Returns the immutable normalized alpha contour used by exact peel completion.

func set_peel(grab_local: Vector2, drag_local: Vector2) -> void: # Updates only the lightweight uniforms needed for the current peel pose.
	_material.set_shader_parameter("grab_local", grab_local) # Sends the original local grab point into the deformation shader.
	_material.set_shader_parameter("drag_local", drag_local) # Sends the current local displacement into the deformation shader.

func clear_peel() -> void: # Returns the shader to the undeformed flat-sticker state.
	_material.set_shader_parameter("drag_local", Vector2.ZERO) # Removes all peel displacement while preserving the last grab point harmlessly.

func set_turnover(grab_local: Vector2, fold_axis_local: Vector2, angle: float) -> void: # Rotates the detached flat sheet around the grabbed material point so its adhesive side turns back to the printed face.
	var axis_3d: Vector3 = Vector3(fold_axis_local.x, 0.0, fold_axis_local.y).normalized() # Converts the in-plane fold axis into the sticker mesh's local 3D coordinates.
	var pivot_3d: Vector3 = Vector3(grab_local.x, 0.0, grab_local.y) # Converts the exact grabbed material point into the mesh's local 3D coordinates.
	var rotation_basis: Basis = Basis(axis_3d, angle) # Creates the requested physical rotation around the fold axis.
	var pivot_offset: Vector3 = pivot_3d - rotation_basis * pivot_3d # Computes the translation required to keep the grabbed material point fixed during rotation.
	transform = Transform3D(rotation_basis, pivot_offset) # Applies the turnover without moving the material point held by the player.

func clear_turnover() -> void: # Returns the detached visual to its normal printed-face-up transform.
	transform = Transform3D.IDENTITY # Removes all temporary turnover rotation and pivot translation.

func _build_grid_mesh() -> ArrayMesh: # Creates a fixed tessellated plane covering exactly the artwork rectangle.
	var vertices: PackedVector3Array = PackedVector3Array() # Stores grid vertex positions across the complete artwork rectangle.
	var normals: PackedVector3Array = PackedVector3Array() # Stores initial upward normals before shader deformation.
	var uvs: PackedVector2Array = PackedVector2Array() # Stores normal zero-to-one artwork coordinates across the sticker surface.
	var indices: PackedInt32Array = PackedInt32Array() # Stores indexed triangles with Godot's clockwise front-face winding.
	var vertex_columns: int = GRID_COLUMNS + 1 # Calculates the number of vertices across the grid including both edges.
	for row: int in range(GRID_ROWS + 1): # Walks every horizontal row of the tessellated sticker.
		var artwork_v: float = float(row) / float(GRID_ROWS) # Converts the row directly into source artwork UV space.
		var local_z: float = (artwork_v - 0.5) * _artwork_size.y # Converts the normalized row into centered physical sticker space.
		for column: int in range(GRID_COLUMNS + 1): # Walks every vertex across the current grid row.
			var artwork_u: float = float(column) / float(GRID_COLUMNS) # Converts the column directly into source artwork UV space.
			var local_x: float = (artwork_u - 0.5) * _artwork_size.x # Converts the normalized column into centered physical sticker space.
			vertices.append(Vector3(local_x, 0.0, local_z)) # Adds one flat material point to the sticker mesh.
			normals.append(Vector3.UP) # Gives the undeformed printed face an upward physical normal.
			uvs.append(Vector2(artwork_u, artwork_v)) # Stores the exact source artwork UV coordinate with no overscan or generated margin.
	for row: int in range(GRID_ROWS): # Walks each grid cell vertically to create indexed triangles.
		for column: int in range(GRID_COLUMNS): # Walks each grid cell horizontally to create indexed triangles.
			var top_left: int = row * vertex_columns + column # Finds the upper-left vertex of the current cell.
			var top_right: int = top_left + 1 # Finds the upper-right vertex of the current cell.
			var bottom_left: int = top_left + vertex_columns # Finds the lower-left vertex of the current cell.
			var bottom_right: int = bottom_left + 1 # Finds the lower-right vertex of the current cell.
			indices.append(top_left) # Begins the first clockwise triangle in the cell.
			indices.append(top_right) # Adds the second vertex of the first triangle.
			indices.append(bottom_right) # Completes the first triangle across the cell diagonal.
			indices.append(top_left) # Begins the second clockwise triangle in the cell.
			indices.append(bottom_right) # Adds the second vertex of the second triangle.
			indices.append(bottom_left) # Completes the second triangle across the remaining half of the cell.
	var arrays: Array = [] # Creates the fixed Godot mesh-array container.
	arrays.resize(Mesh.ARRAY_MAX) # Sizes the container to the complete Mesh.ArrayType layout expected by ArrayMesh.
	arrays[Mesh.ARRAY_VERTEX] = vertices # Supplies procedural positions to the mesh surface.
	arrays[Mesh.ARRAY_NORMAL] = normals # Supplies initial normals to the mesh surface.
	arrays[Mesh.ARRAY_TEX_UV] = uvs # Supplies exact artwork coordinates to the mesh surface.
	arrays[Mesh.ARRAY_INDEX] = indices # Supplies indexed topology to the mesh surface.
	var array_mesh: ArrayMesh = ArrayMesh.new() # Creates the GPU mesh resource that owns the sticker surface.
	array_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays) # Commits the complete tessellated sticker as one efficient triangle surface.
	return array_mesh # Returns the finished static grid ready for shader deformation.

func _build_surface_detail_offset() -> Vector2: # Builds a deterministic-looking procedural-detail offset so sticker wear does not repeat perfectly across copies.
	var instance_seed: float = float(get_instance_id()) # Uses the runtime node identity as cheap per-copy entropy without any global random generator state.
	var offset_x: float = _hash_float(instance_seed * 0.173 + 11.0) # Produces one stable pseudo-random horizontal offset for the realism texture.
	var offset_y: float = _hash_float(instance_seed * 0.379 + 37.0) # Produces one stable pseudo-random vertical offset for the realism texture.
	return Vector2(offset_x, offset_y) * 8.0 - Vector2.ONE * 4.0 # Spreads the procedural wear pattern broadly so duplicates do not share the same fingerprint placement.

func _build_surface_detail_rotation() -> float: # Builds one per-copy procedural-detail rotation so scratches and smudges vary between sticker instances.
	var instance_seed: float = float(get_instance_id()) # Reuses the runtime identity to avoid synchronized detail orientation across duplicates.
	return _hash_float(instance_seed * 0.613 + 73.0) * TAU # Converts a normalized pseudo-random value into a full-angle rotation in radians.

func _hash_float(seed: float) -> float: # Generates a cheap deterministic pseudo-random scalar in the zero-to-one range without allocating a RandomNumberGenerator.
	var hashed_value: float = sin(seed) * 43758.5453123 # Produces the signed pseudo-random source value used by the lightweight per-instance hash.
	return hashed_value - floorf(hashed_value) # Reproduces shader-style fractional behavior with the typed GDScript floor function.
